dist: focal
sudo: true
language: python

matrix:
  include:
  - python: 3.10
    name: "Python310"

before_install:
    - sudo apt-get install libgeos-dev libproj-dev proj-data graphviz libblas-dev liblapack-dev
    - sudo apt-get install graphviz
    - sudo apt-get install protobuf-compiler libprotoc-dev cmake

install:
  - pip install pyquicksetup
  - pip install -r requirements.txt

before_script:
  - python setup.py build_ext --inplace

script:
  - python setup.py unittests -g ".*((LONG)|(SKIP)|(notebooks)).*"
